name: Docker Image Latest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Running this job only for main branch

    steps:
    - name: get-name
      run: |
          echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV

    - uses: actions/checkout@latest

    - name: Build and Publish latest Docker image
      uses: VaultVulp/gp-docker-action@latest
      with:
          github-token: ${{ github.token }}
          image-name: ${{ env.REPO_NAME }}
          dockerfile: Dockerfile
