name: Manual

on:
    workflow_dispatch:

jobs:
    print-name:
        runs-on: ubuntu-latest
        steps:
            - name: Dump github context
              run:   echo "$GITHUB_CONTEXT"
              shell: bash
              env:
               GITHUB_CONTEXT: ${{ toJson(github) }}
            - name: get-name
              run: |
                  echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
            - name: print-REPO_NAME
              run: |
                  echo "${{ env.REPO_NAME }}"
            - name: downcase github.repository
              run: |
                echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}
            - name: print-IMAGE_NAME
              run: |
                  echo "${{ env.IMAGE_NAME }}"
